config/routes.rb
Rails.application.routes.draw do
  get 'teacherv/my_lectures_course_entries'

  get 'teacherv/attending'

  get 'teacherv/teaching'

  resources :attendances
  resources :status_of_attendances
  resources :lecture_course_entries
  get 'teacherv/index'

  get 'son' => 'son#index'
  get 'admin' => 'admin#index'
  get 'parent'=> 'parent#index'
  get 'resume' => 'son#resume'
  get 'addLectureEntry' => 'lecture_course_entry#add'
  get 'teacherv' => 'teacherv#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :type_of_users
  resources :type_of_evaluations
  resources :lecture_courses
  resources :evaluations
  resources :grades
  resources :lectures
  resources :teachers
  resources :notes
  resources :students
  resources :courses
  resources :parents
  get 'home/index'

  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :Status_of_attendance
  belongs_to :Lecture_course_entry
  belongs_to :Student
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :Teacher
  has_many :Students
  has_many :lecture_courses
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :Type_of_evaluation
  belongs_to :Lecture_course
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :Evaluation
  belongs_to :Student
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :Teacher
  has_many :Lecture_courses
end

app/models/lecture_course.rb
class LectureCourse < ApplicationRecord
  belongs_to :Course
  belongs_to :Lecture
  has_many :lecture_course_entries
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :Student
  belongs_to :Lecture_course
end

app/models/parent.rb
class Parent < ApplicationRecord
  belongs_to :User
  has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :Parent
  belongs_to :Course
  has_many :Notes
  has_many :Grades
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :User
  has_many :Lectures
end

app/models/type_of_user.rb
class TypeOfUser < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :Type_of_user
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:date, :description, :Student_id, :Lecture_course_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/parent_helper.rb
module ParentHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/son_helper.rb
module SonHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/notes/_form.html.erb
<%= form_with(model: note, local: true) do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :note_date %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description, id: :note_description %>
  </div>

  <div class="field">
    <%= form.label :Student_id %>
    <%= form.text_field :Student_id, id: :note_Student_id %>
  </div>

  <div class="field">
    <%= form.label :Lecture_course_id %>
    <%= form.text_field :Lecture_course_id, id: :note_Lecture_course_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Notes</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Description</th>
      <th>Student</th>
      <th>Lecture course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.date %></td>
        <td><%= note.description %></td>
        <td><%= note.Student %></td>
        <td><%= note.Lecture_course %></td>
        <td><%= link_to 'Show', note %></td>
        <td><%= link_to 'Edit', edit_note_path(note) %></td>
        <td><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Note', new_note_path %>

app/views/notes/new.html.erb
<h1>New Note</h1>

<%= render 'form', note: @note %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @note.date %>
</p>

<p>
  <strong>Description:</strong>
  <%= @note.description %>
</p>

<p>
  <strong>Student:</strong>
  <%= @note.Student %>
</p>

<p>
  <strong>Lecture course:</strong>
  <%= @note.Lecture_course %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>