config/routes.rb
Rails.application.routes.draw do
  get 'teacherv/my_lectures_course_entries'

  get 'teacherv/attending'

  get 'teacherv/teaching'

  resources :attendances
  resources :status_of_attendances
  resources :lecture_course_entries
  get 'teacherv/index'

  get 'son' => 'son#index'
  get 'admin' => 'admin#index'
  get 'parent'=> 'parent#index'
  get 'resume' => 'son#resume'
  get 'addLectureEntry' => 'lecture_course_entry#add'
  get 'teacherv' => 'teacherv#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :type_of_users
  resources :type_of_evaluations
  resources :lecture_courses
  resources :evaluations
  resources :grades
  resources :lectures
  resources :teachers
  resources :notes
  resources :students
  resources :courses
  resources :parents
  get 'home/index'

  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :Status_of_attendance
  belongs_to :Lecture_course_entry
  belongs_to :Student
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :Teacher
  has_many :Students
  has_many :lecture_courses
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :Type_of_evaluation
  belongs_to :Lecture_course
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :Evaluation
  belongs_to :Student
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :Teacher
  has_many :Lecture_courses
end

app/models/lecture_course.rb
class LectureCourse < ApplicationRecord
  belongs_to :Course
  belongs_to :Lecture
  has_many :lecture_course_entries
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :Student
  belongs_to :Lecture_course
end

app/models/parent.rb
class Parent < ApplicationRecord
  belongs_to :User
  has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :Parent
  belongs_to :Course
  has_many :Notes
  has_many :Grades
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :User
  has_many :Lectures
end

app/models/type_of_user.rb
class TypeOfUser < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :Type_of_user
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/lectures_controller.rb
class LecturesController < ApplicationController
  before_action :set_lecture, only: [:show, :edit, :update, :destroy]

  # GET /lectures
  # GET /lectures.json
  def index
    @lectures = Lecture.all
  end

  # GET /lectures/1
  # GET /lectures/1.json
  def show
  end

  # GET /lectures/new
  def new
    @lecture = Lecture.new
  end

  # GET /lectures/1/edit
  def edit
  end

  # POST /lectures
  # POST /lectures.json
  def create
    @lecture = Lecture.new(lecture_params)

    respond_to do |format|
      if @lecture.save
        format.html { redirect_to @lecture, notice: 'Lecture was successfully created.' }
        format.json { render :show, status: :created, location: @lecture }
      else
        format.html { render :new }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lectures/1
  # PATCH/PUT /lectures/1.json
  def update
    respond_to do |format|
      if @lecture.update(lecture_params)
        format.html { redirect_to @lecture, notice: 'Lecture was successfully updated.' }
        format.json { render :show, status: :ok, location: @lecture }
      else
        format.html { render :edit }
        format.json { render json: @lecture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lectures/1
  # DELETE /lectures/1.json
  def destroy
    @lecture.destroy
    respond_to do |format|
      format.html { redirect_to lectures_url, notice: 'Lecture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lecture
      @lecture = Lecture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lecture_params
      params.require(:lecture).permit(:year, :name, :program, :level, :Teacher_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/lectures_helper.rb
module LecturesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/parent_helper.rb
module ParentHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/son_helper.rb
module SonHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/lectures/_form.html.erb
<%= form_with(model: lecture, local: true) do |form| %>
  <% if lecture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(lecture.errors.count, "error") %> prohibited this lecture from being saved:</h2>

      <ul>
      <% lecture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year, id: :lecture_year %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :lecture_name %>
  </div>

  <div class="field">
    <%= form.label :program %>
    <%= form.text_field :program, id: :lecture_program %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.text_field :level, id: :lecture_level %>
  </div>

  <div class="field">
    <%= form.label :Teacher_id %>
    <%= form.text_field :Teacher_id, id: :lecture_Teacher_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/lectures/edit.html.erb
<h1>Editing Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Show', @lecture %> |
<%= link_to 'Back', lectures_path %>

app/views/lectures/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lectures</h1>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Name</th>
      <th>Program</th>
      <th>Level</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= lecture.year %></td>
        <td><%= lecture.name %></td>
        <td><%= lecture.program %></td>
        <td><%= lecture.level %></td>
        <td><%= lecture.Teacher.last_name %></td>
        <td><%= link_to 'Show', lecture %></td>
        <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecture', new_lecture_path %>

app/views/lectures/new.html.erb
<h1>New Lecture</h1>

<%= render 'form', lecture: @lecture %>

<%= link_to 'Back', lectures_path %>

app/views/lectures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Year:</strong>
  <%= @lecture.year %>
</p>

<p>
  <strong>Name:</strong>
  <%= @lecture.name %>
</p>

<p>
  <strong>Program:</strong>
  <%= @lecture.program %>
</p>

<p>
  <strong>Level:</strong>
  <%= @lecture.level %>
</p>

<p>
  <strong>Teacher:</strong>
  <%= @lecture.Teacher %>
</p>

<%= link_to 'Edit', edit_lecture_path(@lecture) %> |
<%= link_to 'Back', lectures_path %>