config/routes.rb
Rails.application.routes.draw do
  get 'teacherv/my_lectures_course_entries'

  get 'teacherv/attending'

  get 'teacherv/teaching'

  resources :attendances
  resources :status_of_attendances
  resources :lecture_course_entries
  get 'teacherv/index'

  get 'son' => 'son#index'
  get 'admin' => 'admin#index'
  get 'parent'=> 'parent#index'
  get 'resume' => 'son#resume'
  get 'addLectureEntry' => 'lecture_course_entry#add'
  get 'teacherv' => 'teacherv#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :type_of_users
  resources :type_of_evaluations
  resources :lecture_courses
  resources :evaluations
  resources :grades
  resources :lectures
  resources :teachers
  resources :notes
  resources :students
  resources :courses
  resources :parents
  get 'home/index'

  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :Status_of_attendance
  belongs_to :Lecture_course_entry
  belongs_to :Student
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :Teacher
  has_many :Students
  has_many :lecture_courses
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :Type_of_evaluation
  belongs_to :Lecture_course
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :Evaluation
  belongs_to :Student
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :Teacher
  has_many :Lecture_courses
end

app/models/lecture_course.rb
class LectureCourse < ApplicationRecord
  belongs_to :Course
  belongs_to :Lecture
  has_many :lecture_course_entries
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :Student
  belongs_to :Lecture_course
end

app/models/parent.rb
class Parent < ApplicationRecord
  belongs_to :User
  has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :Parent
  belongs_to :Course
  has_many :Notes
  has_many :Grades
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :User
  has_many :Lectures
end

app/models/type_of_user.rb
class TypeOfUser < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :Type_of_user
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)

    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:name, :last_name, :email, :User_id)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/parent_helper.rb
module ParentHelper
end

app/helpers/parents_helper.rb
module ParentsHelper
end

app/helpers/son_helper.rb
module SonHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/teachers/_form.html.erb
<%= form_with(model: teacher, local: true) do |form| %>
  <% if teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :teacher_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :teacher_last_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :teacher_email %>
  </div>

  <div class="field">
    <%= form.label :User_id %>
    <%= form.text_field :User_id, id: :teacher_User_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= teacher.name %></td>
        <td><%= teacher.last_name %></td>
        <td><%= teacher.email %></td>
        <td><%= teacher.User.name %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form', teacher: @teacher %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @teacher.name %>
</p>

<p>
  <strong>Last name:</strong>
  <%= @teacher.last_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @teacher.email %>
</p>

<p>
  <strong>User:</strong>
  <%= @teacher.User %>
</p>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>