config/routes.rb
Rails.application.routes.draw do
  get 'teacherv/my_lectures_course_entries'

  get 'teacherv/attending'

  get 'teacherv/teaching'

  resources :attendances
  resources :status_of_attendances
  resources :lecture_course_entries
  get 'teacherv/index'

  get 'son' => 'son#index'
  get 'admin' => 'admin#index'
  get 'parent'=> 'parent#index'
  get 'resume' => 'son#resume'
  get 'addLectureEntry' => 'lecture_course_entry#add'
  get 'teacherv' => 'teacherv#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  resources :users
  resources :type_of_users
  resources :type_of_evaluations
  resources :lecture_courses
  resources :evaluations
  resources :grades
  resources :lectures
  resources :teachers
  resources :notes
  resources :students
  resources :courses
  resources :parents
  get 'home/index'

  root :to => "home#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :Status_of_attendance
  belongs_to :Lecture_course_entry
  belongs_to :Student
end

app/models/course.rb
class Course < ApplicationRecord
  belongs_to :Teacher
  has_many :Students
  has_many :lecture_courses
end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :Type_of_evaluation
  belongs_to :Lecture_course
end

app/models/grade.rb
class Grade < ApplicationRecord
  belongs_to :Evaluation
  belongs_to :Student
end

app/models/lecture.rb
class Lecture < ApplicationRecord
  belongs_to :Teacher
  has_many :Lecture_courses
end

app/models/lecture_course.rb
class LectureCourse < ApplicationRecord
  belongs_to :Course
  belongs_to :Lecture
  has_many :lecture_course_entries
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :Student
  belongs_to :Lecture_course
end

app/models/parent.rb
class Parent < ApplicationRecord
  belongs_to :User
  has_many :students
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :Parent
  belongs_to :Course
  has_many :Notes
  has_many :Grades
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  belongs_to :User
  has_many :Lectures
end

app/models/type_of_user.rb
class TypeOfUser < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :Type_of_user
  validates :name, presence: true, uniqueness: true
  has_secure_password
end

app/controllers/teacherv_controller.rb
class TeachervController < ApplicationController
  include TeachervHelper
  def index
    set_teacher
    set_curso
    set_lecture
  end

  def teaching
    set_teacher
    set_curso
    set_lecture
    set_lecture_course
    end

  def attending
    set_teacher
    set_curso
    set_lecture
    set_lecture_course
    set_lecture_course_entryn(params[:lectureCouEntId].to_i)
    set_student_attendance_list
  end
  def my_lectures_course_entries
    set_teacher
    set_curso
    set_lecture
    set_lecture_course
    set_lecture_course_entry
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/grades_helper.rb
module GradesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/parent_helper.rb
module ParentHelper
end

app/helpers/son_helper.rb
module SonHelper
end

app/helpers/teacherv_helper.rb
module TeachervHelper
  def set_teacher
    usuarioid = session[:user_id]
    @profe = Teacher.where(User_id: usuarioid)
  end

  def set_curso
    @cursos = Course.where(Teacher_id: @profe[0].id)
  end

  def set_lecture
    @lectures = Lecture.all.where(Teacher_id: @profe[0].id)
  end

  def set_lecture_course
    total_lecture_course = LectureCourse.all
    @lecture_courses = []
    total_lecture_course.each do |l|
      @lecture_courses.push(l) if l.Lecture.Teacher_id == @profe[0].id
    end
end

  def set_lecture_course_entryn(n)
    @lecture_course_entry = LectureCourseEntry.find(n) if n != 0
    set_lecture_course_entry if n == 0
end

  def set_lecture_course_entry
    @lecture_course_entries = LectureCourseEntry.all
    @lecture_course_entries.each do |l|
      unless @lecture_courses.include?(l.Lecture_course)
        @lecture_course_entries.delete(l)
      end
    end
    @lecture_course_entries.sort_by(&:created_at)
    @lecture_course_entry = @lecture_course_entries.last
    end

  def set_student_attendance_list
    students = Student.where(Course_id: @lecture_course_entry)
    attended = Attendance.where(Lecture_course_entry_id: @lecture_course_entry)
    attended = attended.where('DATE(created_at) = ?', Date.today)
    attendedStudent = []
    @studentsList = []

    attended.each do |at|
      attendedStudent.push at.Student
    end

    students.each do |s|
      @studentsList.push(s) unless attendedStudent.include?(s)
    end
    @studentsList
end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/teacherv/_attending.html.erb
<p>Hello from partial _attending</p>
<%set_teacher%>
<%set_lecture_course%>
<%set_lecture_course_entryn(lectureCouEntId)%>
<%set_student_attendance_list%>
<h3> Attendance for  <%=@lecture_course_entry.Lecture_course.Course.level +  @lecture_course_entry.Lecture_course.Course.section + " " + @lecture_course_entry.Lecture_course.Lecture.name%></h3>
<table>
  <thead>
    <tr>
      <th>First Name</th>
      <th>Last Name</th>
      <th colspan="3"></th>
      <th><%= link_to "Change Class", teacherv_my_lectures_course_entries_path %></th>
    </tr>
  </thead>
  <tbody>
    <% if @studentsList != nil %>
    <% @studentsList.each do |s| %>
    <tr>
      <td><%= s.name %></td>
      <td><%= s.last_name %></td>
      <td><%= button_to "Present", attendances_path(Status_of_attendance_id: 1, Lecture_course_entry_id: @lecture_course_entry.id, Student_id: s.id), :locals => {:lectureCouEntId => lectureCouEntId }, :class =>"present", remote: true%></td>
      <td><%= button_to "Absent", attendances_path(Status_of_attendance_id: 2, Lecture_course_entry_id: @lecture_course_entry.id, Student_id: s.id), :locals => {:lectureCouEntId => lectureCouEntId }, :class=>"absent", remote: true%></td>
      <td><%= button_to "Late", attendances_path(Status_of_attendance_id: 3, Lecture_course_entry_id: @lecture_course_entry.id, Student_id: s.id), :locals => {:lectureCouEntId => lectureCouEntId }, :class=>"late", remote: true%></td>
      <td><%= button_to "Excused", attendances_path(Status_of_attendance_id: 4, Lecture_course_entry_id: @lecture_course_entry.id, Student_id: s.id), :locals => {:lectureCouEntId => lectureCouEntId }, :class=>"excused", remote: true%></td>
    </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

app/views/teacherv/_lecture.html.erb
<h3>My Lectures</h3>

<table>
  <thead>
    <tr>
      <th>Year</th>
      <th>Name</th>
      <th>Program</th>
      <th>Level</th>
      <th>Teacher</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @lectures.each do |lecture| %>
      <tr>
        <td><%= lecture.year %></td>
        <td><%= lecture.name %></td>
        <td><%= lecture.program %></td>
        <td><%= lecture.level %></td>
        <td><%= lecture.Teacher.last_name %></td>
        <td><%= link_to 'Show', lecture %></td>
        <td><%= link_to 'Edit', edit_lecture_path(lecture) %></td>
        <td><%= link_to 'Destroy', lecture, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lecture', new_lecture_path %>

app/views/teacherv/attending.html.erb
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
<h1>Teacherv#attending</h1>
<p>Find me in app/views/teacherv/attending.html.erb</p>
<body>
  <div id="pro">
  <%= render :partial=>'teacherv/attending', :locals => {:lectureCouEntId => @lecture_course_entry.id} %>
</div>
</body>

app/views/teacherv/index.html.erb
<h1>Teacherv#index</h1>
<p>Wellcome Mr/Mrs.
  <%=@profe[0].name%>
  <%=@profe[0].last_name%></p>
<h3>My Course</h3>

<table>
  <thead>
    <tr>
      <th>Level</th>
      <th>Section</th>
      <th>Generation</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cursos.each do |course| %>
    <tr>
      <td><%= course.level %></td>
      <td><%= course.section %></td>
      <td><%= course.graduation_year %></td>
      <td><%= link_to 'Show', course %></td>
    </tr>
    <% end %>
  </tbody>
</table>


<%= render "lecture", lectures: @lectures %>

<br>

app/views/teacherv/my_lectures_course_entries.html.erb
<h1>Teacherv#my_lectures_course_entries</h1>
<p>Find me in app/views/teacherv/my_lectures_course_entries.html.erb</p>
<table>
  <thead>
    <tr>
      <th>Course</th>
      <th>Lectures Name</th>
      <th>Number</th>
      <th>Date</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @lecture_course_entries.each do |le| %>
    <tr>
      <td><%= le.Lecture_course.Course.level + le.Lecture_course.Course.section%></td>
      <td><%= le.Lecture_course.Lecture.name%></td>
      <td><%= le.number %></td>
      <td><%= le.date %></td>
      <td><%= le.description %></td>
      <td><%= le.id %></td>
      <td><%= link_to 'Edit', edit_lecture_course_entry_path(le.id) %></td>
      <td><%= link_to 'Attendance', teacherv_attending_path(:lectureCouEntId => le.id)  %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/teacherv/teaching.html.erb
<h1>Teacherv#Teaching</h1>
<p>Find me in app/views/teacherv/teaching.html.erb</p>

  <table>
    <thead>
      <tr>
        <th>Course</th>
        <th>Lecture</th>
        <th>ID</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @lecture_courses.each do |lecture_course| %>
        <tr>
          <td><%= lecture_course.Course.level + lecture_course.Course.section %></td>
          <td><%= lecture_course.Lecture.name %></td>
          <td><%= lecture_course.id %></td>
          <td><%= link_to "add Entry", new_lecture_course_entry_path(lecture_course: lecture_course.id)%></td>
        </tr>
      <% end %>
    </tbody>
  </table>